# https://taskfile.dev

version: "3"

tasks:
  build:
    aliases:
      - default
    cmds:
      - task: rollup-build

  rollup-build:
    sources:
      - index.md
      - js/**/*.js
      - css/**/*.css
      - rollup.config.mjs
    generates:
      - css/style.min.css
      - css/editor.min.css
      - script.min.js
      - script.mins.js.map
    method: timestamp
    cmds:
      - npx rollup --config

  bump:
    generates:
      - VERSION
      - CHANGELOG.md
    cmds:
      - cz bump

  push:
    vars:
      GIT_REPO_NAMES: [apps, avent, avant, github]
    cmds:
      - for: { var: GIT_REPO_NAMES }
        cmd: git push {{.ITEM}} && git push {{.ITEM}} --tags

  tag:
    desc: "Crée un tag avec pour date du tag la date du commit (usage: task tag -- <commit> <tag>)"
    cmds:
      - |
        bash -c '
        set -- {{.CLI_ARGS}}
        COMMIT=$1
        TAG=$2

        if [ -z "$COMMIT" ] || [ -z "$TAG" ]; then
          echo "❌ Usage: task tag -- <commit> <tag>"
          exit 1
        fi

        TAG_DATE=$(git show -s --format=%aD "$COMMIT")
        echo "📌 Création du tag \"$TAG\" sur le commit $COMMIT (date: $TAG_DATE)"
        GIT_COMMITTER_DATE="$TAG_DATE" git tag -a "$TAG" "$COMMIT" -m ""
        '
    silent: false
